IPAdmin/Models/SerialNo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;

namespace IPAdmin.Models
{
    public class SerialNo
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(200)]
        public string SerialNumber { get; set; }
        public Patent Patent { get; set; }
        public DateTime CreateDate { get; set; }

        public ICollection<SerialNoCustomer> SerialNoCustomers { get; set; }
    }
}

IPAdmin/Controllers/CustomerController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using IPAdmin.Common;
using IPAdmin.Filters;
using IPAdmin.Models;
using IPAdmin.Repository;
using WebMatrix.WebData;


namespace IPAdmin.Controllers
{
    [InitializeSimpleMembership]
    [Authorize]
    public class CustomerController : Controller
    {
        //private PatentContext db = new PatentContext();
        private UnitOfWork _unitOfWork;
        private UserProfileRepository _customeRepository;
        //
        // GET: /Customer/

        public CustomerController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _customeRepository = _unitOfWork.UserProfileRepository;
        }

        //[Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            // return all users for admin
            if (Roles.IsUserInRole("Admin"))
                return View(_customeRepository.GetAllActive());

            // return users developed by current user
            var user = _customeRepository.Get( c => c.Id == WebSecurity.CurrentUserId, null, "Customers").FirstOrDefault();
            return View(user.Customers.Where(c => c.IsDeleted == false));
        }

        //
        // GET: /Customer/Details/5

        public ActionResult Details(int id = 0)
        {
            //var customer = (from c in db.UserProfiles.Include(u => u.SerialNoCustomers.Select(sn=>sn.SerialNo)).Include(u=>u.ParentUser)
            //    where c.Id == id
            //    select c).FirstOrDefault();

            //var customer = _customeRepository.Get(c => c.Id == id && !c.IsDeleted, null, "ParentUser, SerialNoCustomers.SerialNo.SerialNoCustomers.Customer").FirstOrDefault();

            var customer = _customeRepository.Get(c => c.Id == id && !c.IsDeleted, null, "ParentUser, SerialNoCustomers.SerialNo.Patent").FirstOrDefault();
            
            if (customer == null)
            {
                return HttpNotFound();
            }

            if (!Roles.IsUserInRole("Admin"))
            {
                // return 404 if current user not the viewed customer's parent or the cus tomer is deleted
                if (customer.ParentUser_Id != WebSecurity.CurrentUserId)
                    return HttpNotFound();
            }
            return View(customer);
        }

        //
        // GET: /Customer/Edit/5

        public ActionResult Edit(int id = 0)
        {
            var customer = _customeRepository.GetByID(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // POST: /Customer/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile customer)
        {
            var dbCustomer = _customeRepository.GetByID(customer.Id);
            if (ModelState.IsValid)
            {
                dbCustomer.UserName = customer.UserName;
                dbCustomer.Address = customer.Address;
                dbCustomer.Company = customer.Company;
                dbCustomer.Email = customer.Email;
                dbCustomer.UpdateDate = DateTime.Now;
                dbCustomer.UpdateBy = Helper.GetCurrentUserName();

                _customeRepository.Update(dbCustomer);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(dbCustomer);
        }

        //
        // GET: /Customer/Delete/5

        public ActionResult Delete(int id = 0)
        {
            var customer = _customeRepository.GetByID(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // POST: /Customer/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var customer = _customeRepository.GetByID(id);
            customer.IsDeleted = true;
            _customeRepository.Update(customer);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

IPAdmin/Controllers/SerialNoController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Configuration;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;
using IPAdmin.Common;
using IPAdmin.Filters;
using IPAdmin.Models;
using IPAdmin.Repository;
using IPAdmin.ViewModels;
using Microsoft.Ajax.Utilities;
using WebGrease.Css.Extensions;
using WebMatrix.WebData;

namespace IPAdmin.Controllers
{
    [InitializeSimpleMembership]
    [Authorize]
    public class SerialNoController : Controller
    {
        private UnitOfWork _unitOfWork;
        private GenericRepository<SerialNo> _serialNoRepository;
        private GenericRepository<SerialNoCustomer> _serialNoCustomerRepository;
        private UserProfileRepository _userProfileRepository;
        //
        // GET: /Customer/

        public SerialNoController(UnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            _serialNoRepository = _unitOfWork.SerialNoRepository;
            _serialNoCustomerRepository = _unitOfWork.SerialNoCustomerRepository;
            _userProfileRepository = _unitOfWork.UserProfileRepository;
        }

        //
        // GET: /SerialNo/id

        public ActionResult Index(int id)
        {
            int userId = WebSecurity.CurrentUserId;

            var snNoCustomers = _serialNoCustomerRepository.Get(s => s.SerialNoId == id, q => q.OrderBy(s => s.Order),
                "SerialNo.Patent, Customer").ToList();

            if (!snNoCustomers.Any())
                return HttpNotFound();

            if (snNoCustomers.Any(sc => sc.CustomerId == userId) == false)
                throw new ApplicationException("Current user is not part of this serial number");

            return View(snNoCustomers);
        }

        public ActionResult Create(int id)
        {
            var serialNo = _serialNoRepository.Get(s => s.Id == id, null, "SerialNoCustomers.Customer").FirstOrDefault();
                if (serialNo == null)
                    return HttpNotFound();

            var allocatedCustomers =_serialNoCustomerRepository.Get(sc => sc.SerialNoId == id && !sc.Customer.IsDeleted).Select(sc => sc.CustomerId).ToArray();
            var candidateCustomers = GetAvailableCustomers(new List<SerialNo>(){serialNo}).Where(c => !allocatedCustomers.Contains(c.UserId)).ToList();

            var ac = new AvailableCustomer {SerialNo = serialNo, Customers = candidateCustomers, SerialNoId = id, Currency = "AUD"};
            return View(ac);
        }

        private IEnumerable<UserRole> GetAvailableCustomers(IEnumerable<SerialNo> serialNoes)
        {
            IList<UserRole> userRoles = new List<UserRole>();

            var currentUser = _userProfileRepository.Get(u => u.Id == WebSecurity.CurrentUserId, null, "Customers").SingleOrDefault();
            if (currentUser == null)
                throw new ApplicationException("Inavlid login user");

            IList<string> lastOrderCustomerRoles = new List<string>();
            foreach (var serialNo in serialNoes)
            {
                var lastOrderUser = serialNo.SerialNoCustomers.Where(sc=>!sc.Customer.IsDeleted).OrderByDescending(s => s.Order).First();
                lastOrderCustomerRoles.Add(Roles.GetRolesForUser(lastOrderUser.Customer.UserName).First());
            }
            
            //lastOrderCustomerRoles.Add(Roles.GetRolesForUser().First());
            //string role = Helper.GetLowestRole(lastOrderCustomerRoles.ToArray());

            // get current user roll
            string role = Roles.GetRolesForUser().FirstOrDefault();
            lastOrderCustomerRoles.Add(role);
            var excludedRoles = Helper.GetExcludedRoles(lastOrderCustomerRoles.Distinct().ToArray()); 

            if (!string.IsNullOrWhiteSpace(role))
            {
                if (role == "Admin")
                {
                    var users = _userProfileRepository.GetAllActive().ToList();

                    if (users != null && users.Any())
                    {
                        userRoles = users.Where(u => !excludedRoles.Contains(Roles.GetRolesForUser(u.UserName).First()))
                                .Select(u => new UserRole(u))
                                .ToList();
                    }
                }
                else if (role == "D1")
                {
                    // can deliver to D2 only
                    userRoles = currentUser.Customers.Where(u => !u.IsDeleted && Roles.IsUserInRole(u.UserName, "D2")).Select(u => new UserRole(u)).ToList();
                }
                else if (role == "D2")
                {
                    // can deliver to M1 only
                    //userRoles = db.UserProfiles.Where(u => Roles.IsUserInRole("M1")).Select(u => new UserRole(u)).ToList();
                    userRoles = currentUser.Customers.Where(u => !u.IsDeleted && Roles.IsUserInRole(u.UserName, "M1")).Select(u => new UserRole(u)).ToList();
                }
                else if (role == "M1")
                {
                    // can deliver to M2 or end user
                    userRoles = currentUser.Customers.Where(u => !u.IsDeleted && Roles.IsUserInRole(u.UserName, "M2") || Roles.IsUserInRole(u.UserName, "EndUser")).Select(u => new UserRole(u)).ToList();
                }
                else if (role == "M2")
                {
                    // can deliver to end user only 
                    userRoles = currentUser.Customers.Where(u => !u.IsDeleted && Roles.IsUserInRole(u.UserName, "EndUser")).Select(u => new UserRole(u)).ToList();
                }
            }
            
            return userRoles;
        }


        [HttpPost]
        public ActionResult Create(AvailableCustomer availableCustomer)
        {
            var sn = _serialNoRepository.GetByID(availableCustomer.SerialNoId);
            if (sn == null)
                return HttpNotFound();

            var customer = _userProfileRepository.GetByID(availableCustomer.SelectedCustomerId);

            int maxOrder =
                _serialNoCustomerRepository.Get(snc => snc.SerialNoId == sn.Id, q => q.OrderBy(snc => snc.Order))
                    .Select(snc => snc.Order)
                    .Max();

            SerialNoCustomer nsc = new SerialNoCustomer
            {
                Customer = customer,
                CustomerId = customer.Id,
                Order = ++maxOrder,
                SerialNo = sn,
                SerialNoId = sn.Id,
                ContractNo = availableCustomer.ContractNo,
                InvoiceNo = availableCustomer.InvoiceNo,
                Currency = availableCustomer.Currency,
                Price = availableCustomer.Price,
                MachineId = (string.IsNullOrWhiteSpace(availableCustomer.MachineId) ? null : availableCustomer.MachineId), 
                CreateDate = DateTime.Now
            };

            _serialNoCustomerRepository.Insert(nsc);
            _unitOfWork.Save();

            return RedirectToAction("Index", new { id = sn.Id });
        }

        [HttpPost]
        public ActionResult AssignCustomer(IEnumerable<SerialNoSelection> selections, string path)
        {
            var serialIds = selections.Where(s => s.Selected).Select(s => s.SerialNo.Id).ToList();
            if (!serialIds.Any())
            {
                TempData["Message"] = "You must select serial numbers first before assign to customer";
                return Redirect(path);
            }

            var serialNos = _serialNoRepository.Get(s => serialIds.Contains(s.Id), null, "Patent, SerialNoCustomers.Customer").ToList();

            var allocatedCustomers = _serialNoCustomerRepository.Get(sc => serialIds.Contains(sc.SerialNoId) && !sc.Customer.IsDeleted).Select(sc => sc.CustomerId).ToArray();
            var candidateCustomers = GetAvailableCustomers(serialNos).Where(c => !allocatedCustomers.Contains(c.UserId)).ToList();

            var ac = new AssignSerialNos() { SerialNo = serialNos, Customers = candidateCustomers, Currency = "AUD"};

            return View(ac);
        }

        [HttpPost]
        public ActionResult DoBatchAssign(AssignSerialNos assignSerialNos)
        {
            foreach (var id in assignSerialNos.SerialNo.Select(s=>s.Id))
            {
                var sn = _serialNoRepository.GetByID(id);
                if (sn == null)
                    throw new ArgumentException(string.Format("Can not find record for Id: {0}", id));

                var customer = _userProfileRepository.GetByID(assignSerialNos.SelectedCustomerId);

                int maxOrder =
                    _serialNoCustomerRepository.Get(snc => snc.SerialNoId == sn.Id, q => q.OrderBy(snc => snc.Order))
                        .Select(snc => snc.Order)
                        .Max();

                SerialNoCustomer nsc = new SerialNoCustomer
                {
                    Customer = customer,
                    CustomerId = customer.Id,
                    Order = ++maxOrder,
                    SerialNo = sn,
                    SerialNoId = sn.Id,
                    ContractNo = assignSerialNos.ContractNo,
                    InvoiceNo = assignSerialNos.InvoiceNo,
                    Currency = String.IsNullOrEmpty(assignSerialNos.Currency) ? "AUD" : assignSerialNos.Currency,
                    Price = assignSerialNos.Price,
                    MachineId = String.IsNullOrEmpty(assignSerialNos.MachineId) ? null : assignSerialNos.MachineId,
                    CreateDate = DateTime.Now
                };

                _serialNoCustomerRepository.Insert(nsc);
            }

            _unitOfWork.Save();

            return RedirectToAction("Index", "Patent");
        }

        public ActionResult PrintChild(int id)
        {
            var customer =_serialNoCustomerRepository.Get(sc => sc.SerialNoId == id, q => q.OrderBy(sc => sc.Order),
                    "Customer, SerialNo, SerialNo.Patent").LastOrDefault();

IPAdmin/Views/SerialNo/AssignCustomer.cshtml
@using Antlr.Runtime
@model IPAdmin.ViewModels.AssignSerialNos

@{
    ViewBag.Title = "AssignSerialNo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Assign SerialNo in Batch</h2>

@using (Html.BeginForm("DoBatchAssign", "SerialNo", new { path = Request.Path }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    if (Model.SerialNo != null && Model.SerialNo.Any())
    {
        <div class="display-field">
            <table id="SerialNumberTable">
                <thead>
                    <tr>
                        <th>
                            Serial Number
                        </th>
                        <th>
                            User Number
                        </th>
                        <th>
                            Current Level
                        </th>
                    </tr>
                </thead>
                @for (int i=0; i<Model.SerialNo.Count; i++)
                {
                    var sn = Model.SerialNo[i];
                    // only show serial number line if current user is one node in the line.
                    var ssn = Roles.IsUserInRole("Admin") ? sn.SerialNoCustomers.FirstOrDefault() : sn.SerialNoCustomers.FirstOrDefault(c => c.CustomerId == WebSecurity.CurrentUserId);
                    if (ssn == null)
                    {
                        continue;
                    }

                    var validSNCustomers = sn.SerialNoCustomers.Where(snc => !snc.Customer.IsDeleted).ToList();

                    <tr>
                        <td>
                            @sn.SerialNumber
                            @Html.HiddenFor(x=>x.SerialNo[i].Id)
                        </td>
                        <td>
                            @{
                                if (validSNCustomers.Any())
                                {
                                    int count = validSNCustomers.Count;
                                    @count
                                    ;
                                    <text> user(s)</text>
                                }
                                else
                                {
                                    <text>0 user</text>
                                }
                            }

                        </td>
                        <td>
                            @Roles.GetRolesForUser(validSNCustomers.OrderByDescending(c => c.Order).First().Customer.UserName).First()
                        </td>
                    </tr>
                }
            </table>
        </div>
    }

    @Html.DropDownListFor(m => m.SelectedCustomerId, new SelectList(Model.Customers, "UserId", "UserAndRole"), "--Select--")
    @Html.ValidationMessageFor(m => m.SelectedCustomerId)

    <div>
        @Html.LabelFor(m => m.ContractNo)
        @Html.EditorFor(m => m.ContractNo)
        @Html.ValidationMessageFor(m => m.ContractNo)
    </div>
    
    <div>
        @Html.LabelFor(m => m.InvoiceNo)
        @Html.EditorFor(m => m.InvoiceNo)
        @Html.ValidationMessageFor(m => m.InvoiceNo)
    </div>

    <div>
        @Html.LabelFor(m => m.Currency)
        @Html.EditorFor(m => m.Currency)
        @Html.ValidationMessageFor(m => m.Currency)
    </div>

    <div>
        @Html.LabelFor(m => m.Price)
        @Html.EditorFor(m => m.Price)
        @Html.ValidationMessageFor(m => m.Price)
    </div>

    <div>
        @Html.LabelFor(m => m.MachineId)
        @Html.EditorFor(m => m.MachineId)
    </div>


    <p>
        <input type="submit" value="Give to customer" />
    </p>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

IPAdmin/Views/SerialNo/Create.cshtml
@model IPAdmin.ViewModels.AvailableCustomer

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Model.SerialNo.SerialNumber<br/>

    @Html.HiddenFor(m=>m.SerialNoId)
    @Html.DropDownListFor(m => m.SelectedCustomerId, new SelectList(Model.Customers, "UserId", "UserAndRole"), "--Select--")

    <div>
        @Html.LabelFor(m => m.ContractNo)
        @Html.EditorFor(m => m.ContractNo)
        @Html.ValidationMessageFor(m => m.ContractNo)
    </div>
    
    <div>
        @Html.LabelFor(m => m.InvoiceNo)
        @Html.EditorFor(m => m.InvoiceNo)
        @Html.ValidationMessageFor(m => m.InvoiceNo)
    </div>

    <div>
        @Html.LabelFor(m => m.Currency)
        @Html.EditorFor(m => m.Currency)
        @Html.ValidationMessageFor(m => m.Currency)
    </div>

    <div>
        @Html.LabelFor(m => m.Price)
        @Html.EditorFor(m => m.Price)
        @Html.ValidationMessageFor(m => m.Price)
    </div>

    <div>
        @Html.LabelFor(m => m.MachineId)
        @Html.EditorFor(m => m.MachineId)
    </div>
    <p>
        <input type="submit" value="Give to customer" />
    </p>
}

@Html.ActionLink("Create new customer", "Create", "Customer")

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

IPAdmin/Views/SerialNo/Index.cshtml
@using IPAdmin.Models
@model IEnumerable<IPAdmin.Models.SerialNoCustomer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SerialNoCustomer snCustomer;
}

<h2>Certify Details</h2>
<br/>

@if (Model.FirstOrDefault() != null)
{
    snCustomer = Model.FirstOrDefault();

    <div class="display-label">
        Patent
    </div>
    @snCustomer.SerialNo.Patent.Name
    <br/><br/>
    <div class="display-label">
        Serial Number
    </div>
    @snCustomer.SerialNo.SerialNumber
}

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.Company)
        </th>
        <th>
            Customer Type
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContractNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InvoiceNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Currency)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MachineId)
        </th>
    </tr>

    @foreach (var item in Model.Where( c => c.Customer.IsDeleted == false))
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Customer.UserName)
            </td>
            <td>
                @Html.DisplayFor(model => item.Customer.Company)
            </td>
            <td>
                @Roles.GetRolesForUser(item.Customer.UserName).FirstOrDefault()
            </td>
            <td>
                @Html.DisplayFor(model=>item.ContractNo)
            </td>
            <td>
                @Html.DisplayFor(model=>item.InvoiceNo)
            </td>
            <td>
                @Html.DisplayFor(model => item.Currency)
            </td>
            <td>
                @Html.DisplayFor(model => item.Price)
            </td>
            <td>
                @Html.DisplayFor(model => item.MachineId)
            </td>
        </tr>
    }
    
</table>

<br/>
<br/>

@if (Model.FirstOrDefault() != null)
{
    snCustomer = Model.FirstOrDefault();
    @Html.ActionLink("Give to customer", "Create", new {id = snCustomer.SerialNoId}) <br/>
    @Html.ActionLink("Print", "PrintChild", new {id=snCustomer.SerialNoId})

}